version: 2
jobs:
        build:
                docker:
                        - image: circleci/go:1.11
                steps:
                        - checkout
                        - run: echo "Hello world!"
